version: '3.8'

services:
  llm-service:
    build: .
    container_name: llm-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # 로그 파일 영속성 유지
      - ./logs:/app/logs
      # config.yaml 마운트 (실시간 설정 변경 가능)
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
